client_id = "c698cff46abdcc8e7b41cb1a0c3b099d"
name = "OrderSight Inventory Insights"
application_url = "https://order-inventory-insights.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_inventory,read_locations,read_orders"

[auth]
redirect_urls = [
  "https://order-inventory-insights.onrender.com/auth/callback",
  "https://order-inventory-insights.onrender.com/auth/shopify/callback",
  "https://order-inventory-insights.onrender.com/api/auth/callback"
]

